"""Added is_read to notifications

Revision ID: b997ebcc018a
Revises: 
Create Date: 2026-04-20 09:52:12.967413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b997ebcc018a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('news_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_expires_at')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('code_expires_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('news_ibfk_4'), 'match', ['match_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
